import { Animal, User } from '../App';

export const mockAnimals: Animal[] = [
  {
    id: '1',
    name: 'Raja',
    species: 'Bengal Tiger',
    number: 1,
    image: 'https://images.unsplash.com/photo-1727036752580-957404758267?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0aWdlciUyMHdpbGRsaWZlfGVufDF8fHx8MTc2MjAwMzA2NXww&ixlib=rb-4.1.0&q=80&w=1080',
    health: 'excellent',
    lastChecked: '2 hours ago',
    assignedTo: 'Ramesh Kumar',
    mood: 'Active',
    appetite: 'Good',
  },
  {
    id: '2',
    name: 'Ganesha',
    species: 'Asian Elephant',
    number: 2,
    image: 'https://images.unsplash.com/photo-1662141048384-b4061a402097?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxlbGVwaGFudCUyMHpvb3xlbnwxfHx8fDE3NjIwMDMwNjV8MA&ixlib=rb-4.1.0&q=80&w=1080',
    health: 'good',
    lastChecked: '4 hours ago',
    assignedTo: 'Ramesh Kumar',
    mood: 'Calm',
    appetite: 'Excellent',
  },
  {
    id: '3',
    name: 'Simba',
    species: 'African Lion',
    number: 1,
    image: 'https://images.unsplash.com/photo-1680858592943-dd599a244ea8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsaW9uJTIwd2lsZGxpZmV8ZW58MXx8fHwxNzYxOTk4Mjk5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    health: 'fair',
    lastChecked: '1 day ago',
    assignedTo: 'Priya Sharma',
    mood: 'Lazy',
    appetite: 'Low',
    notes: 'Monitor appetite closely',
  },
  {
    id: '4',
    name: 'Gigi',
    species: 'Giraffe',
    number: 3,
    image: 'https://images.unsplash.com/photo-1647687646732-aa5884d6fe1d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnaXJhZmZlJTIwem9vfGVufDF8fHx8MTc2MjAwMzA2Nnww&ixlib=rb-4.1.0&q=80&w=1080',
    health: 'excellent',
    lastChecked: '30 mins ago',
    assignedTo: 'Ramesh Kumar',
    mood: 'Playful',
    appetite: 'Good',
  },
  {
    id: '5',
    name: 'Bao',
    species: 'Giant Panda',
    number: 1,
    image: 'https://images.unsplash.com/photo-1703248187251-c897f32fe4ec?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYW5kYSUyMGJlYXJ8ZW58MXx8fHwxNzYyMDAzMDY2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    health: 'good',
    lastChecked: '6 hours ago',
    assignedTo: 'Priya Sharma',
    mood: 'Sleepy',
    appetite: 'Good',
  },
  {
    id: '6',
    name: 'Zara',
    species: 'Plains Zebra',
    number: 2,
    image: 'https://images.unsplash.com/photo-1638910939569-7f88cf71ebbc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx6ZWJyYSUyMHdpbGRsaWZlfGVufDF8fHx8MTc2MTk2NzEwMXww&ixlib=rb-4.1.0&q=80&w=1080',
    health: 'excellent',
    lastChecked: '3 hours ago',
    assignedTo: 'Ramesh Kumar',
    mood: 'Active',
    appetite: 'Excellent',
  },
];

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Ramesh Kumar',
    role: 'zookeeper',
    permissions: ['view_animals', 'update_logs', 'upload_media'],
    password: 'zoo123',
  },
  {
    id: '2',
    name: 'Dr. Anjali Patel',
    role: 'vet',
    permissions: ['view_health', 'prescribe', 'view_logs'],
    password: 'vet123',
  },
  {
    id: '3',
    name: 'Rajiv Singh',
    role: 'admin',
    permissions: ['all'],
    password: 'admin123',
  },
  {
    id: '4',
    name: 'Officer Mehta',
    role: 'officer',
    permissions: ['view_food', 'view_costs'],
    password: 'officer123',
  },
  {
    id: '5',
    name: 'Priya Sharma',
    role: 'zookeeper',
    permissions: ['view_animals', 'update_logs', 'upload_media'],
    password: 'zoo456',
  },
];

export const translations = {
  en: {
    login: 'Login',
    selectRole: 'Select Your Role',
    zookeeper: 'Zookeeper',
    admin: 'Admin',
    vet: 'Vet Doctor',
    officer: 'Forest Officer',
    dashboard: 'Dashboard',
    myAnimals: 'My Animals',
    dailyLog: 'Daily Log',
    emergency: 'Emergency',
    settings: 'Settings',
    health: 'Health',
    excellent: 'Excellent',
    good: 'Good',
    fair: 'Fair',
    poor: 'Poor',
    lastChecked: 'Last Checked',
    addLog: 'Add Log',
    viewProfile: 'View Profile',
    todaysTasks: "Today's Tasks",
    pendingLogs: 'Pending Logs',
    users: 'Users',
    animals: 'Animals',
    alerts: 'Alerts',
    manageUsers: 'Manage Users',
    addAnimal: 'Add Animal',
    healthReports: 'Health Reports',
    voiceLogs: 'Voice Logs',
    feedingData: 'Feeding Data',
    foodCost: 'Food Cost',
    logout: 'Logout',
    language: 'Language',
    notifications: 'Notifications',
    recordVoice: 'Record Voice Note',
    recording: 'Recording',
    playback: 'Playback',
    save: 'Save',
    cancel: 'Cancel',
    mood: 'Mood',
    appetite: 'Appetite',
    movement: 'Movement',
    injuries: 'Injuries',
    uploadImage: 'Upload Image',
    uploadVideo: 'Upload Video',
    shareWith: 'Share With',
    submit: 'Submit',
    sosAlert: 'SOS Alert',
    confirmSOS: 'Confirm Emergency Alert',
    sendAlert: 'Send Alert',
  },
  hi: {
    login: 'लॉगिन',
    selectRole: 'अपनी भूमिका चुनें',
    zookeeper: 'जूकीपर',
    admin: 'एडमिन',
    vet: 'पशु चिकित्सक',
    officer: 'वन अधिकारी',
    dashboard: 'डैशबोर्ड',
    myAnimals: 'मेरे जानवर',
    dailyLog: 'दैनिक लॉग',
    emergency: 'आपातकाल',
    settings: 'सेटिंग्स',
    health: 'स्वास्थ्य',
    excellent: 'उत्कृष्ट',
    good: 'अच्छा',
    fair: 'ठीक',
    poor: 'खराब',
    lastChecked: 'अंतिम जांच',
    addLog: 'लॉग जोड़ें',
    viewProfile: 'प्रोफ़ाइल देखें',
    todaysTasks: 'आज के कार्य',
    pendingLogs: 'लंबित लॉग',
    users: 'उपयोगकर्ता',
    animals: 'जानवर',
    alerts: 'अलर्ट',
    manageUsers: 'उपयोगकर्ता प्रबंधित करें',
    addAnimal: 'जानवर जोड़ें',
    healthReports: 'स्वास्थ्य रिपोर्ट',
    voiceLogs: 'वॉयस लॉग',
    feedingData: 'भोजन डेटा',
    foodCost: 'भोजन लागत',
    logout: 'लॉगआउट',
    language: 'भाषा',
    notifications: 'सूचनाएं',
    recordVoice: 'वॉयस नोट रिकॉर्ड करें',
    recording: 'रिकॉर्डिंग',
    playback: 'प्लेबैक',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    mood: 'मूड',
    appetite: 'भूख',
    movement: 'गति',
    injuries: 'चोट',
    uploadImage: 'छवि अपलोड करें',
    uploadVideo: 'वीडियो अपलोड करें',
    shareWith: 'साझा करें',
    submit: 'जमा करें',
    sosAlert: 'एसओएस अलर्ट',
    confirmSOS: 'आपातकालीन अलर्ट की पुष्टि करें',
    sendAlert: 'अलर्ट भेजें',
  },
};
